export const FETCH_CONFIRMED_CASES_START =
  'covid19/FETCH_CONFIRMED_CASES_START'
export const FETCH_CONFIRMED_CASES_SUCCESS =
  'covid19/FETCH_CONFIRMED_CASES_SUCCESS'
export const FETCH_CONFIRMED_CASES_FAILURE =
  'covid19/FETCH_CONFIRMED_CASES_FAILURE'
